#!/usr/bin/env bash
# ----------------------------------------------------------------------
# obsidian-init.sh — Set up Obsidian vault config for a km knowledge base
# Usage: obsidian-init.sh [--update] [target-dir]
# ----------------------------------------------------------------------
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
UPDATE=false
TARGET_DIR="."

for arg in "$@"; do
    case "$arg" in
        --update) UPDATE=true ;;
        *)        TARGET_DIR="$arg" ;;
    esac
done

TARGET_DIR="$(cd "$TARGET_DIR" && pwd)"

# -- Colors ------------------------------------------------------------
GREEN='\033[0;32m'
YELLOW='\033[0;33m'
RED='\033[0;31m'
NC='\033[0m'

ok()   { echo -e "  ${GREEN}✓${NC} $1"; }
skip() { echo -e "  ${YELLOW}→${NC} $1 (already exists)"; }
fail() { echo -e "  ${RED}✗${NC} $1"; exit 1; }

# -- Prerequisite check ------------------------------------------------
if [ ! -f "$TARGET_DIR/CONVENTIONS.md" ]; then
    fail "CONVENTIONS.md not found in $TARGET_DIR — run /km init first"
fi

if [ "$UPDATE" = true ]; then
    echo "Updating Obsidian vault config in $TARGET_DIR..."
else
    echo "Initializing Obsidian vault in $TARGET_DIR..."
fi

# -- .obsidian/ directory ----------------------------------------------
mkdir -p "$TARGET_DIR/.obsidian/snippets"
ok ".obsidian/ directory"

# -- app.json ----------------------------------------------------------
cat > "$TARGET_DIR/.obsidian/app.json" << 'APPJSON'
{
  "useMarkdownLinks": true,
  "newLinkFormat": "relative",
  "showFrontmatter": true,
  "readableLineLength": true,
  "strictLineBreaks": true,
  "foldHeading": true,
  "foldIndent": true,
  "defaultViewMode": "preview",
  "alwaysUpdateLinks": true
}
APPJSON
ok "app.json (standard markdown links, reading mode)"

# -- appearance.json ---------------------------------------------------
cat > "$TARGET_DIR/.obsidian/appearance.json" << 'APPEARANCEJSON'
{
  "cssTheme": "",
  "enabledCssSnippets": ["km-status"]
}
APPEARANCEJSON
ok "appearance.json (km-status snippet enabled)"

# -- snippets/km-status.css -------------------------------------------
CSS_TEMPLATE="$SCRIPT_DIR/obsidian-km-status.template.css"
if [ -f "$CSS_TEMPLATE" ]; then
    cp "$CSS_TEMPLATE" "$TARGET_DIR/.obsidian/snippets/km-status.css"
    ok "snippets/km-status.css"
else
    echo -e "  ${YELLOW}✗${NC} template not found at $CSS_TEMPLATE — skipping CSS snippet"
fi

# -- graph.json --------------------------------------------------------
HAS_BRAINS=false
if [ -d "$TARGET_DIR/brains" ]; then
    HAS_BRAINS=true
fi

if [ "$HAS_BRAINS" = true ]; then
    cat > "$TARGET_DIR/.obsidian/graph.json" << 'GRAPHJSON'
{
  "colorGroups": [
    { "query": "path:inbox/", "color": { "a": 1, "rgb": 16753920 } },
    { "query": "tag:#decision", "color": { "a": 1, "rgb": 3381759 } },
    { "query": "tag:#concept", "color": { "a": 1, "rgb": 65280 } },
    { "query": "file:_index", "color": { "a": 1, "rgb": 16777215 } },
    { "query": "path:brains/", "color": { "a": 1, "rgb": 10092543 } }
  ],
  "showTags": true,
  "showAttachments": false,
  "showOrphans": true,
  "showArrow": true
}
GRAPHJSON
    ok "graph.json (with brains color group)"
else
    cat > "$TARGET_DIR/.obsidian/graph.json" << 'GRAPHJSON'
{
  "colorGroups": [
    { "query": "path:inbox/", "color": { "a": 1, "rgb": 16753920 } },
    { "query": "tag:#decision", "color": { "a": 1, "rgb": 3381759 } },
    { "query": "tag:#concept", "color": { "a": 1, "rgb": 65280 } },
    { "query": "file:_index", "color": { "a": 1, "rgb": 16777215 } }
  ],
  "showTags": true,
  "showAttachments": false,
  "showOrphans": true,
  "showArrow": true
}
GRAPHJSON
    ok "graph.json"
fi

# -- community-plugins.json -------------------------------------------
echo '[]' > "$TARGET_DIR/.obsidian/community-plugins.json"
ok "community-plugins.json"

# -- .gitignore --------------------------------------------------------
GITIGNORE="$TARGET_DIR/.gitignore"
MARKER="# Obsidian vault config"

if [ -f "$GITIGNORE" ] && grep -qF "$MARKER" "$GITIGNORE"; then
    skip ".gitignore Obsidian block"
else
    cat >> "$GITIGNORE" << 'GITIGNOREBLOCK'

# Obsidian vault config (generated by /km obsidian init)
.obsidian/workspace*.json
.obsidian/cache
.obsidian/plugins/
.obsidian/themes/
.obsidian/hotkeys.json
.obsidian/core-plugins.json
.obsidian/core-plugins-migration.json
GITIGNOREBLOCK
    ok ".gitignore updated"
fi

# -- Summary -----------------------------------------------------------
echo ""
echo -e "${GREEN}Done!${NC} Open this folder in Obsidian to browse your knowledge base."
echo ""
echo "Graph view color legend:"
echo -e "  🟠 inbox/     — triage zone"
echo -e "  🔵 #decision  — architecture decisions"
echo -e "  🟢 #concept   — concepts and ideas"
echo -e "  ⚪ _index     — navigation hubs"
if [ "$HAS_BRAINS" = true ]; then
    echo -e "  🟣 brains/    — linked knowledge bases"
    echo ""
    echo "Note: brain submodules must be initialized for their content to appear:"
    echo "  git submodule update --init"
fi
echo ""
echo "Recommended community plugins (install via Obsidian Settings):"
echo "  • Dataview — query/filter documents by frontmatter"
echo "  • Frontmatter Tag Suggest — autocomplete for tags"
